apiVersion: batch/v1
kind: CronJob
metadata:
  name: classcronjob
spec:
  schedule: "*/2 * * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jobcontainer
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Cinny Abraham
          restartPolicy: OnFailure
