apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: autoscale-app-hpa
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: autoscale-app
    minReplicas: 2
    maxReplicas: 6
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
