apiVersion: apps/v1 
kind: Deployment
metadata:
  name: autoscale-app
spec: 
  selector:
    matchLabels:
      app: autoscale
      env: training
  replicas: 2
  template:
    metadata:
      labels:
        app: autoscale
        env: training
    spec:
      containers:
      - name: nodejs-loop
        image: coursedemos/nodejs-loop:v1  # image in Dockerhub
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"

